FROM arm64v8/ros:humble
# FROM osrf/ros:humble-desktop-full
RUN chmod +x ros_entrypoint.sh

WORKDIR /home/asv_workspace

ENV QT_X11_NO_MITSHM=1
ENV EDITOR=nano
ENV XDG_RUNTIME_DIR=/tmp
ENV ROS_DOMAIN_ID=42
RUN apt-get update && apt-get install -y \
    cmake \
    curl \
    nano \
    python3-pip \
    python3-pydantic \
    ruby-dev \
    wget \
    xorg-dev \
    iputils-ping 

RUN apt install ros-humble-mavros -y
RUN wget https://raw.githubusercontent.com/mavlink/mavros/ros2/mavros/scripts/install_geographiclib_datasets.sh
RUN chmod +x install_geographiclib_datasets.sh
RUN /bin/bash -c "./install_geographiclib_datasets.sh"

# Download with wget the latest version of geographiclib
RUN pip3 install setuptools==58.2.0

# TODO: Estas dependencias se meteran en un dependencies.txt
RUN pip3 install bluerobotics-ping 
RUN pip3 install "paho-mqtt<2.0.0"
RUN pip3 install pyserial
RUN pip3 install getmac
RUN pip3 install scipy


RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 1883 1880 5688 5678

COPY ./asv_workspace_local /home/asv_workspace

RUN /bin/bash -c "source /opt/ros/humble/setup.bash; colcon build"
RUN echo 'alias source_ros2="source /opt/ros/humble/setup.bash && source install/setup.bash"' >> .bashrc


CMD ["/bin/bash", "-c", ". ./exec_system.sh"]





