ARG IMAGE_NAME=stereolabs/zedbot:zed-ros2-wrapper_l4t35_1_humble_

FROM ${IMAGE_NAME}

WORKDIR /usr/local/zed/settings/
RUN wget -O  SN35913645.conf http://calib.stereolabs.com/?SN=35913645
RUN wget -O  SN36011585.conf  http://calib.stereolabs.com/?SN=36011585

WORKDIR /root/ros2_ws
ENV ROS_DOMAIN_ID=42
ENTRYPOINT ["/sbin/ros_entrypoint.sh"]
CMD ["bash"]