FROM syanes/asv_us:amd_backbone

EXPOSE 1883 1880 5688 5678

COPY ./asv_workspace /home/asv_workspace

RUN /bin/bash -c "source /opt/ros/humble/setup.bash; colcon build"


ENTRYPOINT ["/sbin/ros_entrypoint.sh"]
CMD ["bash"]