FROM nodered/node-red

# Copy package.json to the WORKDIR so npm builds all of your added nodes modules for Node-RED
WORKDIR /data
COPY package.json /data

# Change ownership of the /data directory to the Node-RED user
USER root
RUN chown -R node-red:node-red /data

# Switch to the Node-RED user
USER node-red

RUN npm install 

# Set the WORKDIR for Node-RED
WORKDIR /usr/src/node-red

# Note: Do not copy settings and flow files here; we'll use an external volume instead
# COPY settings.js /data/settings.js
# COPY flows_cred.json /data/flows_cred.json
# COPY flows.json /data/flows.json
